### ISSUE TITLE
Document the long-term strategy for disentangling the AMP runtime from the Google AMP Cache

### ISSUE THREAD

**Issue by tobie** [ampproject/wg-caching#13]
See:

*  [A CDN for the AMP runtime section](https://gist.github.com/tobie/b5ce633d2622ca4f28e8374d9de8bdf5#a-cdn-for-the-amp-runtime) in the OpenJS Foundation application.
* The FAQ on the [OpenJS Foundation announcement](https://openjsf.org/blog/2019/10/10/openjs-foundation-welcomes-amp-project-to-help-improve-user-experience-on-the-web/):
  
  > **Currently, the AMP runtime is hosted on the same infrastructure as the Google AMP Cache. Doesn’t this present serious issues?**
  >
  > The end goal is to separate the AMP runtime from the Google AMP Cache. The Project is currently in the incubating stage and Project leaders are still determining the next steps. Ideally, hosting and deployment of the AMP runtime to the CDN would fall under the purview of the OpenJS Foundation, much like the foundation is handling other projects CDNs, such as the jQuery CDN.  
  >
  > Untangling the runtime from the cache is a complex endeavor requiring significant investments of time and effort which would be planned and implemented in collaboration with the foundation and industry stakeholders during and after incubation.
  >
  > The OpenJS Foundation CPC is committed to having a long-term strategy in place to address this issue by the end of AMP’s incubation.

This should notably:

- be done in collaboration with the foundation and the CPC,
- describe the difference between the proprietary AMP caches, such as Google's or Bing's, and the hosting of the AMP runtime,
- include a projected timeframe for dis-entangling the two,
- specify the domain(s) on which the AMP runtime would be hosted,
- clarify that AMP caches would probably host their own copy of the runtime (and that cached AMP pages would be transformed accordingly as part of the pre-caching transform process), 
- describe by whom the supporting infrastructure would be provided, how it would be maintained, and how it would be governed,
- describe the deployment process and related security considerations, and
- describe the privacy policy under which the runtime would be hosted.

**Comment by Gregable** [comment]
See [Disentangling the AMP runtime from the Google AMP Cache](https://docs.google.com/document/d/1IMfhVgxCRW0Cq1N7xvflfcoxGdnVshvA92je_wDxAY0/edit?usp=sharing) for the draft design. After some discussion, we decided to propose that the foundation register a new domain name rather than transferring ampproject.org, but both options are discussed in detail in the linked document.

**Comment by tobie** [comment]
Agreement to share this document with the CPC to get feedback. @jorydotcom will share with the CPC copying @Gregable and @tobie (I will share email addresses privately).

**Comment by tobie** [comment]
Document shared late March. CPC emailed with follow-up question. @Gregable to get back to the CPC.

**Comment by tobie** [comment]
@jorydotcom to get back to the CPC and advise AMP infra will be moving ahead with the agreed plan if there aren't further comments or questions.

**Comment by tobie** [comment]
Confirmation from @joesepi that he was OK with the plan. Closing.
